config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "pages#home"

  resource :profile, only: [:show]

  resources :teams, only: [:index,:create,:show] do
    resources :contracts, only: [:create]
  end
  resources :contracts, only: [:index]

  namespace :owner do
    resources :teams, only: [:index, :new, :create]
    resources :contracts, only: [:update, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :renter, class_name: "User"
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_one_attached :photo
  belongs_to :owner, class_name: "User"
  has_many :contracts

  def owner_photo_url
    if photo.attached?
      photo.variant(resize: "398x295").url
    else
      ActionController::Base.helpers.asset_url("teams.png")
    end
  end

  include PgSearch::Model

  pg_search_scope :search_by_dungeon_type_and_success_rate,
                against: [ :dungeon_type, :success_rate, :name, :price_per_day ],
                using: {
                tsearch: { prefix: true } # <-- now `superman batm` will return something!
                }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :teams, foreign_key: :owner_id
  has_many :contracts, foreign_key: :renter_id
  has_many :contracts_as_owner, through: :teams, source: :contracts, class_name: "Contract"
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
    @contracts = current_user.contracts
  end

  def new
    @contract = Contract.new
  end

  def create
    @team = Team.find(params[:team_id])
    @contract = Contract.new(contracts_params)
    @contract.team = @team
    @contract.renter = current_user
    @contract.status = "En attente"
    @total_day = (@contract.begin_date.jd..@contract.end_date.jd).count
    @total_price = @total_day * @team.price_per_day
    @contract.total_price = @total_price
    if @contract.save
      redirect_to contracts_path(@contracts)
    else

      render :new, status: :unprocessable_entity
    end
  end

  private

  def contracts_params
    params.require(:contract).permit(:renter_id, :team_id, :begin_date, :end_date, :status, :total_price)
  end
end

app/controllers/owner/contracts_controller.rb
class Owner::ContractsController < ApplicationController
  def index
    @user_contracts = current_user.contracts_as_owner
  end

  def update
    @contract = Contract.find(params[:id])
    @contract.update(user_contracts_params)

    if @contract.status == "accepted"
      flash[:success] = "Contrat accepté"
      redirect_to owner_contracts_path
    else

      flash[:danger] = "Contrat refusé"
      redirect_to owner_contracts_path
    end
  end

  private

  def user_contracts_params
    params.require(:contract).permit(:status, :id)
  end
end

app/controllers/owner/teams_controller.rb
module Owner
  class TeamsController < ApplicationController
    def index
      @user_teams = current_user.teams
    end

    def new
      @team = Team.new
    end

    def create
      @team = Team.new(team_params)
      @team.owner = current_user
      if @team.save!
        redirect_to owner_teams_path(@team.owner)
      else
        render :new, status: :unprocessable_entity
      end
    end

    def team_params
      params.require(:team).permit(:name, :description, :price_per_day, :dungeon_type, :photo)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @user = current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @teams = Team.all
    if params[:query].present?
      @teams = Team.search_by_dungeon_type_and_success_rate(params[:query])
    else
      @teams = Team.all
    end
  end

  def show
    @team = Team.find(params[:id])
    @contract = Contract.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/index.html.erb
<div class="container padding-title">
  <div class="border-title-reservation"><h1 class=" ml-2">Mes réservations </h1> </div>
  <div class="col container-contracts mt-4">
    <%@contracts.each do |contract| %>
      <div class="card card-contracts" style="width: 400px;">
    <%= link_to team_path(contract.team), style:"text-decoration: none" do%>
        <%= cl_image_tag contract.team.photo.key, class: "card-img-top team-image"   %>
          <div class="card-body">
            <h2 class="card-title"> ⚔️  <%= link_to contract.team.name, contract.team, class: "teams-link", style:"text-decoration: none" %></h2>
            <p id="card-link" class="card-text justify-content-end">💰<strong> <%= contract.total_price %> ₡</strong></p>
            <p class="card-text">Début de quête : <%= contract.begin_date %></p>
            <p class="card-text">Fin de quête : <%= contract.end_date %></p>
            <% if  contract.status == "En attente" %>
              <div class="d-flex justify-content-around text-info">En attente</div>
              <% elsif contract.status == "accepted" %>
              <div class="d-flex justify-content-around text-success">Accepté</div>
              <% else %>
              <div class="d-flex justify-content-around text-danger">Refusé</div>
            <% end %>
          </div>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airdnd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless params[:action] == 'home' || devise_controller? %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>
    <%= yield %>
    <% unless params[:action] == 'home' || devise_controller? %>
      <%= render "shared/footer" %>
    <% end %>
  </body>
</html>

app/views/owner/contracts/index.html.erb
<div class="container padding-title">
  <div class="border-user-teams"><h1>Mes contrats</h1></div>
  <div class="card-user-teams mt-4">
    <% @user_contracts.each do |user_contract|%>
        <div class="card card-user-team" style="width: 400px;">
        <%= cl_image_tag user_contract.team.photo.key, class: "card-img-top team-image"  %>
          <div class="card-body">
            <h2 class="card-title">⚔️ <%= user_contract.team.name %></h2>
            <p class="card-text">💰 <%= user_contract.total_price %> ₡</p>
            <p class="card-text">Début de quête : <%= user_contract.begin_date %></p>
            <p class="card-text">Fin de quête : <%= user_contract.end_date %></p>
            <% if  user_contract.status == "En attente" %>
              <div class="d-flex justify-content-around">
                <%= simple_form_for [:owner, user_contract] do |f| %>
                  <%= f.input :status, label: false, input_html: {value: 'accepted', class:"d-none", }%>
                  <%= f.button :submit, "Accepter", class: "btn btn-info accepter" %>
                <% end %>
                <%= simple_form_for [:owner, user_contract] do |f| %>
                  <%= f.input :status, label: false, input_html: {value: 'refused', class:"d-none", }%>
                  <%= f.button :submit, "Refuser", class: "btn btn-info accepter" %>
                <% end %>
              </div>
            <% elsif user_contract.status == "accepted" %>
              <div class="d-flex justify-content-around text-success">Accepté</div>
              <% else %>
              <div class="d-flex justify-content-around text-danger">Refusé</div>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/owner/teams/create.html.erb
<h1>Owner::Teams#create</h1>
<p>Find me in app/views/owner/teams/create.html.erb</p>

app/views/owner/teams/index.html.erb
<div class="container padding-title">
  <div class="border-user-teams"><h1>Mes équipes</h1></div>
  <div class="card-user-teams mt-4">
    <% @user_teams.each do |user_team|%>
      <% if user_team.photo.attached? %>
        <%= link_to team_path(user_team), style:"text-decoration: none" do%>
          <div class="card card-user-team" style="width: 400px;">
            <%= cl_image_tag user_team.photo.key, class: "card-img-top user-team-image"  %>
            <div class="card-body">
              <h2 class="card-title">⚔️ <%= user_team.name %></h2>
              <p class="card-text">🔥 <%= user_team.success_rate %> / 5</p>
              <p class="card-text">🏰 <%= user_team.dungeon_type %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/owner/teams/new.html.erb
<div>
  <div class= "container bg-img d-flex justify-content-center ">
    <div  class= "container bloc-form body-img col-6 p-5">
      <div class="d-flex justify-content-center">
        <h2 class="m-5 h2-new">Nouvelle Equipe</h2>
      </div>
    <%= simple_form_for([:owner, @team]) do |f| %>

    <%# name %>
      <%= f.input :name, label: "Nom",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "Entrez le nom votre équipe"%>

    <%# description %>
      <%= f.input :description, label: "Description",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "Entrez la description de cette équipe"%>

    <%# price %>
      <%= f.input :price_per_day, label: "Prix par jour",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "Entrez le prix a la journée"%>

    <%# donjon %>
      <%= f.input :dungeon_type, label: "Type de Donjon favoris",label_html: { style: "text-shadow: 0px 2px 3px black;" }, prompt: "Faite vore choix", collection: ["Commun","Héroïque", "Légendaire"], class: "select-placeholder-color"%>

    <%# photo %>
    <div class="form-group">
        <%= f.label :photo, label: "Photo",label_html: { style: "text-shadow: 0px 2px 3px black;" }, placeholder: "Ajoutez une photo a votre équipe", class: "text-imput" %>
        <br>
        <%= f.file_field :photo, class: 'form-control-file' %>
      </div>

      <%# submit btn %>
      <div class="d-flex justify-content-center mt-5">
        <%= f.button :submit, "Creer une équipe", label: "Nouvelle équipe", placeholder: "Nouvelle équipe", class: "btn btn-primary"%>
      </div>
    <% end %>

    <%# retour au profile %>
      <div class="d-flex justify-content-center">
        <%= link_to "retourner au profile", profile_path, class: "back-btn p-4"%>
      </div>
    </div>
  </div>
</div>

app/views/pages/_banner_homepage.html.erb
<div class="banner-homepage" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner-bg.png"%>); height: 100vh;">
  <div class="container banner-top">
    <%= image_tag "logo.png", class: "banner-logo" %>
    <ul class="navbar-nav ">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag @user.avatar.key, class: "user-picture-home", width: 100, height: 100, crop: :fill%>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "banner-login" %>
      <% end %>
    </ul>
  </div>
  <div class="container container-banner-home">
    <h1><strong>AIR DnD</strong></h1>
    <h3>Engage l'équipe de tes rêves</h3>
    <p>🔥 Mets toutes les chances de ton côté !🔥</p>
  </div>
  <div class ="container container-banner-button" style="padding-bottom: 7em;">
    <%= link_to "Partez à l'aventure", teams_path, class: "bannerlink" %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'banner_homepage' %>

app/views/profiles/show.html.erb
<div class="nav-profile d-flex justify-content-center ">
  <div class="d-flex p-3">
    <%= cl_image_tag @user.avatar.key, class: "user-picture", width: 200, height: 200, crop: :fill%>
      <h3 class="align-self-center user-name p-5"><%= @user.name %></h3>
  </div>
</div>

<div class="container d-flex justify-content-center gap-3 p-3">

  <div class="row col-3">
    <%= link_to new_owner_team_path, class:"card profile-card" do %>
      <%= image_tag "new-team.png", class: "profile-img" %>
      <div class="card-body">
        <h5 class="card-title">Créer une équipe</h5>
        <p class="card-text">Rassembler vos troupes! Créer une nouvelle équipe légendaire.</p>
      </div>
    <% end %>
  </div>

  <div class="row col-3">
    <%= link_to owner_contracts_path, class:"card profile-card" do %>
      <%= image_tag "request.png", class: "profile-img" %>
      <div class="card-body">
        <h5 class="card-title">Vos contrats</h5>
        <p class="card-text">Gérer les contrats de vos équipes en cours, et passé.</p>
      </div>
    <% end %>
  </div>


  <div class="row col-3">
    <%= link_to owner_teams_path, class:"card profile-card" do %>
      <%= image_tag "teams.png", class: "profile-img" %>
      <div class="card-body">
        <h5 class="card-title">Vos équipes</h5>
        <p class="card-text">Consulter le statut de vos équipes.</p>
      </div>
    <% end %>
  </div>

  <div class="row col-3">
    <%= link_to contracts_path, class:"card profile-card" do %>
      <%= image_tag "contrats.png", class: "profile-img" %>
      <div class="card-body">
        <h5 class="card-title">Vos réservations</h5>
        <p class="card-text">Gérer le statut de vos réservation auprès d'autre propriétaire.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fa-solid fa-shield"></i></a>
    <a href="#"><i class="fa-solid fa-beer-mug-empty"></i></a>
    <a href="#"><i class="fa-solid fa-fire"></i></a>
    <a href="#"><i class="fa-solid fa-chess-rook"></i></a>
    <a href="#"><i class="fas fa-skull"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fa-solid fa-dragon"></i> Air Dnd, partenaire de vos quêtes depuis 3500 ans <i class="fa-solid fa-dragon fa-flip-horizontal"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "image-brand"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag current_user.avatar.key, class: "avatar-navbar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path, class:"dropdown-item" %>
              <%= link_to "Contrats", owner_contracts_path, class:"dropdown-item" %>
              <%= link_to "Mes équipes", owner_teams_path, class:"dropdown-item" %>
              <%= link_to "Mes réservations", contracts_path, class:"dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %><li class="nav-item">
      </ul>
    </div>
  </div>
</div>